---
title: "Spring 2023 data analysis"
output: pdf_document
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, 
                      fig.height=3, fig.width=5, fig.align = "center")
library(tidyverse) 
library(infer)
library(broom)
library(lubridate)
library(readxl)
```

import data file
```{r}
abs_raw <- read_excel("2023-03-8 third trial 72hr.xlsx",
                          range = "B36:CU901")
colnames(abs_raw)[2] <- "temp"


lum_raw <- read_excel("2023-03-8 third trial 72hr.xlsx",
                          range = "B905:CU1770")
colnames(lum_raw)[2] <- "temp"
```

Declare well
```{r}
MK62 = c("B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10")
MK63 = c("C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10")
MK64 = c("D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10")
MK65 = c("E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10")
MK66 = c("F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10")
MK67 = c("G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10")
unused = c("A4", "A5", "F1", "H1")
control = c("A1", "A2", "A3", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "B1", "B12", "C1", "C12", "D1", "D12", "E1", "E12", "F12", "G1", "G12", "H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10", "H11", "H12", "B11","C11", "D11", "E11", "F11", "G11")
```

normalized time/pivot table
```{r}
abs_with_time <- abs_raw %>%
  mutate(Time = Time[1] %--% Time)

abs_df <- abs_with_time %>% 
  pivot_longer(
    cols = !Time & !temp, 
    names_to = "well", 
    values_to = "absorbance"
  )

lum_with_time <- lum_raw %>%
  mutate(Time = Time[1] %--% Time)

lum_df <- lum_with_time %>% 
  pivot_longer(
    cols = !Time & !temp, 
    names_to = "well", 
    values_to = "luminescence"
  )
```


Normalized background abs
```{r}
control_df <- which((abs_df$Time > 1440 & abs_df$Time < 2880) & abs_df$well %in% control)
abs_df[control_df,]$absorbance
mean(abs_df[control_df,]$absorbance)
```

normalized the data
```{r}
abs_lum <- cbind(abs_df, lum_df[4])

normalized_lum <- abs_lum %>%
  mutate(normalized = luminescence/absorbance,
         strain = case_when(
           well %in% MK62 ~ "MK62",
           well %in% MK63 ~ "MK63",
           well %in% MK64 ~ "MK64",
           well %in% MK65 ~ "MK65",
           well %in% MK66 ~ "MK66",
           well %in% MK67 ~ "MK67",
           well %in% unused ~ "unused",
           well %in% control ~ "control"),
         species = case_when(
           well %in% MK62 ~ "E. coli",
           well %in% MK63 ~ "E. coli",
           well %in% MK64 ~ "E. coli",
           well %in% MK65 ~ "E. clocae",
           well %in% MK66 ~ "E. clocae",
           well %in% MK67 ~ "E. clocae",
           well %in% unused ~ "unused",
           well %in% control ~ "control"),
         promoter = case_when(
           well %in% MK62 ~ "no promoter",
           well %in% MK63 ~ "E. coli promoter",
           well %in% MK64 ~ "E. clocae promoter",
           well %in% MK65 ~ "no promoter",
           well %in% MK66 ~ "E. coli promoter",
           well %in% MK67 ~ "E. clocae promoter",
           well %in% unused ~ "unused",
           well %in% control ~ "control"))
```

Choose only used well
```{r}
correct_well_data <- normalized_lum %>%
  filter(strain != "unused")
```

Plot things out
```{r}
ggplot(data = correct_well_data) + 
  geom_point(mapping = aes(x = Time, y = normalized, shape = species, color = strain)) +
  scale_shape_manual(values=c(1, 2, 3))+
  xlab("Time (min)") +
  ylab("normalized luminescence") +
  ggtitle("third trial")
```


Plot raw abs out
```{r}
raw_data_plot <- normalized_lum %>%
  filter(species != "unused")

ggplot(data = raw_data_plot) + 
  geom_point(mapping = aes(x = Time, y = absorbance, color = strain, shape = promoter))+
  scale_shape_manual(values=c(1, 2, 3, 4))+
  xlab("Time (min)") +
  ylab("raw absorbance") +
  ggtitle("Raw absorbance third trial")
```

Plot raw lum out
```{r}
ggplot(data = raw_data_plot) + 
  geom_point(mapping = aes(x = Time, y = luminescence, shape = species, color = strain)) +
  scale_shape_manual(values=c(1, 2, 3))+
  xlab("Time (min)") +
  ylab("luminescence") +
  ggtitle("Raw luminescence third trial")
```

plot log scale
```{r}
ggplot(data = correct_well_data) + 
  geom_point(mapping = aes(x = Time, y = normalized, shape = species, color = strain)) +
  scale_shape_manual(values=c(1, 2, 3))+
  scale_y_continuous(trans = 'log10') +
  xlab("Time (min)") +
  ylab("normalized luminescence (log10)") +
  ggtitle("Third trial")
```

Plot raw abs log out
```{r}
raw_data_plot <- normalized_lum %>%
  filter(species != "unused")

ggplot(data = raw_data_plot) + 
  geom_point(mapping = aes(x = Time, y = absorbance, color = strain, shape = promoter))+
  scale_shape_manual(values=c(1, 2, 3, 4))+
  scale_y_continuous(trans = 'log10') +
  xlab("Time (min)") +
  ylab("raw absorbance (log10)") +
  ggtitle("Raw absorbance third trial")
```

Plot raw lum log out
```{r}
ggplot(data = raw_data_plot) + 
  geom_point(mapping = aes(x = Time, y = luminescence, shape = species, color = strain)) +
  scale_shape_manual(values=c(1, 2, 3))+
  scale_y_continuous(trans = 'log10') +
  xlab("Time (min)") +
  ylab("luminescence (log10)") +
  ggtitle("Raw luminescence third trial")
```